baseurl = "./"
#baseurl = "https://dlksmc.github.io/page/"
publishDir = "docs"
DefaultContentLanguage = "en"
title = "DL;DS"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Params]
  homeTitle = "DL;DS"
  subtitle = "Dan LaBar; Data Scientist"
  mainSections = ["post","posts"]
  logo = "img/embiggenData.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  #dateFormat = "2020-01-01"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Dan LaBar"
  website = "yourwebsite.com"
  email = "danielrlabar@gmail.com"
  #facebook = "username"
  #github = "dlksmc"
  #gitlab = "username"
  #bitbucket = "username"
  twitter = "embiggenData"
  #reddit = "username"
  linkedin = "dan-labar-b4b6b54"
  #xing = "username"
  stackoverflow = "users/1344789/dnlbrky"
  #snapchat = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"
  #500px = "username"
  #codepen = "username"
  #mastodon = "url"
  #kaggle = "username"
  #weibo = "username"
  #slack = "username"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/index.html"
    weight = 3

#[[menu.main]]
#    identifier = "samples"
#    name = "Samples"
#    weight = 2
#
#[[menu.main]]
#    parent = "samples"
#    name = "Big Image Sample"
#    url = "post/2017-03-07-bigimg-sample"
#    weight = 1
#
#[[menu.main]]
#    parent = "samples"
#    name = "Math Sample"
#    url = "post/2017-03-05-math-sample"
#    weight = 2
#
#[[menu.main]]
#    parent = "samples"
#    name = "Code Sample"
#    url = "post/2016-03-08-code-sample"
#    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
